server:
  port: 8702 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8701/eureka/
      
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest      

mail: gmail.com
